# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type check
        run: npm run tsc --noEmit

      - name: Run ESLint
        run: npm run lint
